{"name": "test_three", "status": "failed", "statusDetails": {"message": "AssertionError: assert [1, 2] == [1, 3]\n  At index 1 diff: 2 != 3\n  Use -v to get the full diff", "trace": "self = <testcase.test_pytest_object.TestPytestObject2 object at 0x10ba684a8>\n\n    def test_three(self):\n>       assert [1,2] == [1,3]\nE       assert [1, 2] == [1, 3]\nE         At index 1 diff: 2 != 3\nE         Use -v to get the full diff\n\ntestcase/test_pytest_object.py:16: AssertionError"}, "attachments": [{"name": "log", "source": "68d32e90-a758-4ba7-8b75-8cf6f27ffb35-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "f087dea6-579d-4809-9c52-3bffdc2f29b3-attachment.txt", "type": "text/plain"}], "start": 1574315562095, "stop": 1574315562095, "uuid": "f42b3d69-0e6b-42a8-a027-0edffc9472de", "historyId": "6baf23e5524dc7b17b158a8a68145120", "testCaseId": "e14a3996a855149e2365268fe70b0ffb", "fullName": "testcase.test_pytest_object.TestPytestObject2#test_three", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_pytest_object"}, {"name": "subSuite", "value": "TestPytestObject2"}, {"name": "host", "value": "lvdeMacBook-Pro.local"}, {"name": "thread", "value": "61486-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_pytest_object"}]}